### ISSUE TITLE
Error when importing module

### ISSUE THREAD

**Issue by stefan-karlsson** [successful-solutions/slab-logging#1]
Getting a error when trying to import library from another application.

```
ERROR in ./node_modules/@slab/logging/logger.ts
Module build failed: Error: node_modules\@slab\logging\logger.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:625:23)
    at plugin.done.then (@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/core/core.module.ts 18:0-58
 @ ./src/app/core/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by stefan-karlsson** [comment]
This has been fixed. I was packing the wrong files =)
